POST http://localhost:3306/v1/pets
Content-Type: application/json

{
    "name": "Brisius",
    "dob": "2010",
    "client_email": "brisius@gmail",
    "archived": 0
}
###

GET http://localhost:3306/v1/pets
###
DELETE http://localhost:3306/v1/pets/4
###

POST http://localhost:3306/v1/meds
Content-Type: application/json

{
    "name": "pyrantel",
    "description": "effective against ascarids, hookworms and stomach worms"
}

###

GET http://localhost:3306/v1/meds
###