POST http://localhost:3306/v1/pets
Content-Type: application/json

{
    "name": "Milka",
    "dob": "2022",
    "client_email": "milka@gmail",
    "archived": 0
}
###

GET http://localhost:3306/v1/pets
###
DELETE http://localhost:3306/v1/pets/4
###
# ====================================================

POST http://localhost:3306/v1/meds
Content-Type: application/json

{
    "name": "pyrantel",
    "description": "effective against ascarids, hookworms and stomach worms"
}

###
GET http://localhost:3306/v1/meds
###
# ========================================================
POST http://localhost:3306/v1/logs
Content-Type: application/json

{
    "pet_id": 8,
    "description": "neduoda sokoladinio pieno",
    "status": "ieskom priezasties"
}

###

GET http://localhost:3306/v1/logs
###